//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaptistHealthEntities : DbContext
    {
        public BaptistHealthEntities()
            : base("name=BaptistHealthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<EMP_LOGIN> EMP_LOGIN { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RFI> RFIs { get; set; }
        public virtual DbSet<RFI_INVITE> RFI_INVITE { get; set; }
        public virtual DbSet<RFP> RFPs { get; set; }
        public virtual DbSet<RFP_INVITE> RFP_INVITE { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATEs { get; set; }
        public virtual DbSet<VENDOR> VENDOR { get; set; }
        public virtual DbSet<VENDOR_LOGIN> VENDOR_LOGIN { get; set; }
    }
}
