//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaptistHealthEntities : DbContext
    {
        public BaptistHealthEntities()
            : base("name=BaptistHealthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> CONTRACTS { get; set; }
        public virtual DbSet<EMP_LOGIN> EMP_LOGIN { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<ITEM> ITEMS { get; set; }
        public virtual DbSet<Report> REPORTS { get; set; }
        public virtual DbSet<RFI> RFIS { get; set; }
        public virtual DbSet<RFI_INVITE> RFI_INVITE { get; set; }
        public virtual DbSet<RFP> RFPS { get; set; }
        public virtual DbSet<RFP_INVITE> RFP_INVITE { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATES { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<VENDOR_LOGIN> VENDOR_LOGIN { get; set; }
    }
}
