//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> reportID { get; set; }
        public Nullable<int> templateID { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
