//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public ITEM()
        {
            this.VENDORs = new HashSet<VENDOR>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemCategory { get; set; }
    
        public virtual ICollection<VENDOR> VENDORs { get; set; }
    }
}
