//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFI
    {
        public RFI()
        {
            this.RFI_INVITE = new HashSet<RFI_INVITE>();
        }
    
        public int RFI_ID { get; set; }
    
        public virtual ICollection<RFI_INVITE> RFI_INVITE { get; set; }
    }
}
