//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFI_INVITE
    {
        public int RFI_ID { get; set; }
        public int Vendor_ID { get; set; }
        public int TemplateID { get; set; }
        public int ReportID { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual RFI RFI { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
    }
}
