//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public TEMPLATE()
        {
            this.Contracts = new HashSet<Contract>();
            this.RFI_INVITE = new HashSet<RFI_INVITE>();
            this.RFP_INVITE = new HashSet<RFP_INVITE>();
        }
    
        public int templateID { get; set; }
        public string TemplateName { get; set; }
        public byte[] TemplateFile { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<RFI_INVITE> RFI_INVITE { get; set; }
        public virtual ICollection<RFP_INVITE> RFP_INVITE { get; set; }
    }
}
