//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_LOGIN
    {
        public int Vendor_ID { get; set; }
        public string Vendor_Username { get; set; }
        public string Vendor_Password { get; set; }
    
        public virtual VENDOR VENDOR { get; set; }
    }
}
