//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rfp_mgmt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Admin
    {
        public int EmployeeID { get; set; }
        public bool Active { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
