// Class File: Employee.cs
// Purpose: This class represents a model for an employee in the RFP Management System.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace rfp_mgmt_system.Models
{
    public class Employee
    {
        // Property: EmployeeID
        // Description: This property uniquely identifies the Employee.
        public int EmployeeID { get; set; }

        // Property: LastName
        // Description: This property stores the last name of the Employee.
        public string LastName { get; set; }

        // Property: FirstName
        // Description: This property stores the first name of the Employee.
        public string FirstName { get; set; }

        // Property: Title
        // Description: This property stores the title of the Employee, which describes their role in the company.
        public string Title { get; set; }

        // Property: Email
        // Description: This property stores the email address of the Employee.
        public string Email { get; set; }

        // Property: Username
        // Description: This property stores the username of the Employee, which is used to log in to the system.
        public string Username { get; set; }

        // Property: Password
        // Description: This property stores the password of the Employee, which is used to log in to the system.
        public string Password { get; set; }

        // Property: Privilege
        // Description: This property stores the privilege level of the Employee, which determines which functions the employee can access.
        public string Privilege { get; set; }

        // Property: SecurityQuestion
        // Description: This property stores the security question for the Employee.  This is used in the event that a password needs to be reset.
        public string SecurityQuestion { get; set; }

        // Property: SecurityAnswer
        // Description: This property stores the security answer for the Employee.  This is used in the event that a password needs to be reset.
        public string SecurityAnswer { get; set; }

        // Property: ResetCode
        // Description: This property store the reset code for the Employee, which is used in the event of a password reset. It will be randomly
        //              generated by the system.
        public string ResetCode { get; set; }

        // Property: List<Contract>
        // Description: This is an array of all the contracts that the Employee is associated with.
        public List<Contract> Contracts { get; set; }

        // Property: List<RFP>
        // Description: This is an array of all the RFPs that the Employee is associated with.
        public List<RFP> RFPs { get; set; }

        // Property: List<Vendors>
        // Description: This is an array of all the vendors that the Employee has approved the status of.
        public List<Vendor> Vendors { get; set; }

    }
}